### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by Andrek25** [wvanbergen/chunky_png#144] opened 2019-12-05 14:17 UTC
I'm trying to paste a series of 875 images into a single image, each image has a size of 256x256 for a total size of 11008x6400, when i try to paste i get this error:

C:/Ruby24/lib/ruby/gems/2.4.0/gems/chunky_png-1.3.11/lib/chunky_png/canvas/png_encoding.rb:220:in `block in encode_png_image_pass_to_stream': failed to allocate memory (NoMemoryError)

And when i try to save the single image i get this error: [FATAL] failed to allocate memory

Is there a way to do it like a IO Stream?
Is there a memory leak in Chunky PNG?
I have 4GB(using 3GB) of Memory Ram, Windows 7 (32 bits).

Example Code:

```
require 'chunky_png'

WIDTH = 11008
HEIGHT = 6400
FOLDER = "images/"

x = 0
y = 0
count = 0
filename_size = Dir.entries(FOLDER).size - 2 # 875 Files.
background = ChunkyPNG::Image.new(WIDTH, HEIGHT, ChunkyPNG::Color::TRANSPARENT)

for filename in Dir.entries(FOLDER) - [".", ".."]
	image = ChunkyPNG::Image.from_file("#{FOLDER}#{filename}") # NoMemoryError.
	background.replace!(image, x * 256, y * 256)
	count += 1
	puts "#{filename} saved! #{count}/#{filename_size} files left."
	x = (x + 1) % (WIDTH / 256)
	if x == 0
		y += 1
	end
	#break if count == 300 # To get '[FATAL] failed to allocate memory' error.
end

puts "Saving background image."
background.save("background.png") # [FATAL] failed to allocate memory.
```

**Comment by CalebSordelet** [comment] 2020-05-13 04:05
At the moment the library could not possibly do this, it loads each of those images into a stream, the issue is an unsigned int has a maximum value of a little over 2,000,000,000 while all of your 875 256x256 images would amount up to 57344000, thus the NoMemoryException occurs because ruby cannot write anymore information to temporary memory. Theoretically the library could be rewritten to write the output as it receives input information, but it would be a lot of work to rewrite such a large portion of the gem. Hope this helps ;-)

**Comment by Nakilon** [comment] 2020-05-14 19:19
Try the https://github.com/libvips/ruby-vips

**Comment by wvanbergen** [comment] 2020-10-23 15:13
Closing this, as this is not a memory leak as explained in https://github.com/wvanbergen/chunky_png/issues/144#issuecomment-627731925

While it could be possible to have a more memory efficient implementation to help with tasks like this, it would require a significant rewrite of large parts of the codebase, which is not something I am planning to do any time soon.

**Closed by wvanbergen** 2020-10-23 15:13 UTC
